project:
  type: website
  output-dir: ../docs

website:
  title: "The world of actors"
  sidebar:
    tools:
    - icon: github
      href: https://github.com/epfl-ada/ada-2022-project-teamlovelace
    style: docked
    search: true
    contents:
      - index.qmd
      - section: Data story
        contents:
          - full_network.ipynb
          - belgian.ipynb
          - growth.ipynb
          - homophily.ipynb
          - centrality_and_success.ipynb
          - conclusion.qmd
      - viz.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



